function plot_segments(figure1, time2, segment, ymin, ylength)

%Time2: time in minutes or seconds, size of segment
%Segment: discretized signal with three levels: 1 (=white), 2 (=blue) and 3 (=red)


abox(2) = ymin;
abox(4) = ylength;               % Get box height
type=segment(1);
abox(1)=time2(1);
for i=1:length(segment)
    if segment(i)~=type;
        abox(3) = time2(i)-abox(1);
        if type==3 % high motion
            an=annotation(figure1,'rectangle',...
                'LineStyle','none',...
                'FaceAlpha',0.2,...
                'FaceColor',[1 0 0]);
            set(an,'parent',gca);
            set(an,'position',abox);
        elseif type==2 % low motion
            abox(3) = time2(i)-abox(1);
            an=annotation(figure1,'rectangle',...
                'LineStyle','none',...
                'FaceAlpha',0.2,...
                'FaceColor',[0 0 1]);
            set(an,'parent',gca);
            set(an,'position',abox);
        elseif type==4 || type==5  %interventions
            an=annotation(figure1,'rectangle',...
                'LineStyle','none',...
                'FaceAlpha',0.2,...
                'FaceColor',[0 0 0]);
            set(an,'parent',gca);
            set(an,'position',abox);
        elseif type==7 % ignored data
            an=annotation(figure1,'rectangle',...
                'LineStyle','none',...
                'FaceAlpha',0.2,...
                'FaceColor',[0.6 0.6 0.6]);
            set(an,'parent',gca);
            set(an,'position',abox);
        elseif type==6 %ghosts
            an=annotation(figure1,'rectangle',...
                'LineStyle','none',...
                'FaceAlpha',0.2,...
                'FaceColor',[0 1 0]);
            set(an,'parent',gca);
            set(an,'position',abox);
        else
            %type==1, no motion, white area
        end
        type = segment(i);
        abox(1) = time2(i);
    end
end

% force ending the last rectangle
abox(3) = time2(i)-abox(1);
if type==3 % high motion
    an=annotation(figure1,'rectangle',...
        'LineStyle','none',...
        'FaceAlpha',0.2,...
        'FaceColor',[1 0 0]);
    set(an,'parent',gca);
    set(an,'position',abox);
elseif type==2 % low motion
    abox(3) = time2(i)-abox(1);
    an=annotation(figure1,'rectangle',...
        'LineStyle','none',...
        'FaceAlpha',0.2,...
        'FaceColor',[0 0 1]);
    set(an,'parent',gca);
    set(an,'position',abox);
elseif type==4 || type==5  %interventions
    an=annotation(figure1,'rectangle',...
        'LineStyle','none',...
        'FaceAlpha',0.2,...
        'FaceColor',[0 0 0]);
    set(an,'parent',gca);
    set(an,'position',abox);
elseif type==7 % ignored data
    an=annotation(figure1,'rectangle',...
        'LineStyle','none',...
        'FaceAlpha',0.2,...
        'FaceColor',[0.6 0.6 0.6]);
    set(an,'parent',gca);
    set(an,'position',abox);
elseif type==6 %ghosts
    an=annotation(figure1,'rectangle',...
        'LineStyle','none',...
        'FaceAlpha',0.2,...
        'FaceColor',[0 1 0]);
    set(an,'parent',gca);
    set(an,'position',abox);
else
    %type==1, no motion, white area
end